#:kivy 1.0.9
#:import HoverButton main.HoverButton

ScreenManager:
    MenuScreen:
        name: 'main_menu'
    CharacterCreation:
        name: 'character_creation'
    InGameScreen:
        name: 'ingame'

<MenuScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: 100, 200, 100, 180
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: 'Program_Files/main_menu_images/main_menu_background.jpg'

        HoverButton:
            text: 'New'
            font_name: 'Program_Files/fonts/medieval_font_file_2.ttf'
            font_size: 70
            size_hint: 0.2, 0.3
            pos_hint: {'center_x': 0.38}
            default_image: 'Program_Files/main_menu_images/original_button_image.png'
            hover_image: 'Program_Files/main_menu_images/new_game_button.png'
            background_color: [0, 0, 0, 0]
            background_normal: ''
            on_press: root.change_to_chat()

        HoverButton:
            text: 'Load'
            font_name: 'Program_Files/fonts/medieval_font_file_2.ttf'
            font_size: 70
            size_hint: 0.2, 0.3
            pos_hint: {'center_x': 0.62}
            default_image: 'Program_Files/main_menu_images/original_button_image.png'
            hover_image: 'Program_Files/main_menu_images/load_game_button.png'
            background_color: [0, 0, 0, 0]
            background_normal: ''
            on_press: app.stop()

        HoverButton:
            text: 'Die'
            font_size: 70
            font_name: 'Program_Files/fonts/medieval_font_file_2.ttf'
            size_hint: 0.2, 0.3
            pos_hint: {'center_x': 0.49}
            default_image: 'Program_Files/main_menu_images/original_button_image.png'
            hover_image: 'Program_Files/main_menu_images/exit_game_button.png'
            background_color: [0, 0, 0, 0]
            background_normal: ''
            on_press: app.stop()

<CharacterCreation>:
    FloatLayout:
        # Background Image with animation enabled
        Image:
            source: 'Program_Files/character_creation_images/character_creation_background.gif'
            allow_stretch: True
            keep_ratio: False
            anim_delay: 0.01

        # Title Image placed above the background image with a black background
        RelativeLayout:
            size_hint: 1, None
            height: 100  # Adjust height to account for padding
            pos_hint: {'top': 0.985}
            padding: [0, 20, 0, 0]  # Padding from the top (left, top, right, bottom)
            canvas.before:
                Color:
                    rgba: 0, 0, 0, 1  # Black color
                Rectangle:
                    pos: self.pos
                    size: self.size

            Image:
                source: 'Program_Files/character_creation_images/character_creation_title.png'  # Replace with your image path
                allow_stretch: True
                keep_ratio: True
                pos_hint: {'center_x': 0.5, 'top': 1}  # Adjust as necessary
        BoxLayout:
            orientation: 'vertical'

            BoxLayout:
                orientation: 'horizontal'

                BoxLayout:
                    orientation: 'vertical'
                    size_hint_x: 0.3
                    padding: [20, 100, 0, 100]
                    spacing: 10

                    # RelativeLayout to add a background image
                    RelativeLayout:
                        size_hint_y: 0.33  # Adjust to cover both the text input and label
                        padding: [0, 0, 0, 0]

                        # Background image behind the text input and label
                        Image:
                            source: 'Program_Files/character_creation_images/info_scroll.png'  # Path to your background image
                            allow_stretch: True
                            keep_ratio: False
                            pos_hint: {'center_x': 0.5, 'center_y': 0.5}

                        # TextInput for character name - single line and constrained to borders
                        TextInput:
                            id: char_name_input
                            hint_text: 'Enter Name'
                            multiline: False  # Keep input to a single line
                            font_name: 'Program_Files/fonts/medieval_font_file_2.ttf'
                            font_size: 24
                            size_hint: (0.8, 0.43)  # Reduced width with size_hint_x set to 0.8
                            pos_hint: {'top': 1, 'center_x': 0.5}  # Center horizontally
                            halign: 'center'
                            padding: [30, 70, 30, 0]  # Adjust padding to keep text within borders
                            foreground_color: (0, 0, 0, 1)  # Black text color
                            background_color: (1, 1, 1, 0)  # Fully transparent background
                            background_normal: ''  # Remove default background image
                            on_text: root.on_char_name_input(self.text)

                        # Stats Label - now positioned below the TextInput
                        Label:
                            id: stats_widget
                            text: '[color=#ff0000]DMG: 0[/color]\n[color=#00ff00]HP: 0[/color]\n[color=#d3d3d3]ARMOR: 0[/color]'
                            markup: True
                            size_hint_y: 0.57
                            pos_hint: {'y': 0}  # Positioned below the TextInput
                            font_size: 20
                            color: (0, 0, 0, 1)
                            halign: 'center'
                            padding: [0, 0, 0, 70]  # 20 pixels padding at the bottom

                    Image:
                        id: character_image
                        source: ''
                        allow_stretch: True
                        keep_ratio: True
                        size_hint_y: 0.66

                BoxLayout:
                    orientation: 'vertical'
                    size_hint_x: 0.64

                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint: (1, 0.3)
                        spacing: 0
                        padding: [50, 150, 50, 20]

                        RelativeLayout:
                            Image:
                                id: female_gif
                                source: 'Program_Files/character_creation_images/1_inactive_female.gif'
                                anim_delay: 0.05
                                allow_stretch: True
                                keep_ratio: True

                            ToggleButton:
                                id: female_button
                                group: 'gender'
                                background_color: (0, 0, 0, 0)
                                background_normal: ''
                                on_press: root.select_gender('female')

                        RelativeLayout:
                            Image:
                                id: male_gif
                                source: 'Program_Files/character_creation_images/2_inactive_male.gif'
                                anim_delay: 0.05
                                allow_stretch: True
                                keep_ratio: True

                            ToggleButton:
                                id: male_button
                                group: 'gender'
                                background_color: (0, 0, 0, 0)
                                background_normal: ''
                                on_press: root.select_gender('male')

                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint: (1, 0.3)
                        spacing: 0
                        padding: [30, 0, 30, 0]

                        RelativeLayout:
                            Image:
                                id: human_gif
                                source: 'Program_Files/character_creation_images/3_inactive_human.gif'
                                anim_delay: 0.05
                                allow_stretch: True
                                keep_ratio: True

                            ToggleButton:
                                id: human_button
                                group: 'species'
                                background_color: (0, 0, 0, 0)
                                background_normal: ''
                                on_press: root.select_species('human')

                        RelativeLayout:
                            Image:
                                id: elf_gif
                                source: 'Program_Files/character_creation_images/4_inactive_elf.gif'
                                anim_delay: 0.05
                                allow_stretch: True
                                keep_ratio: True

                            ToggleButton:
                                id: elf_button
                                group: 'species'
                                background_color: (0, 0, 0, 0)
                                background_normal: ''
                                on_press: root.select_species('elf')

                        RelativeLayout:
                            Image:
                                id: dwarf_gif
                                source: 'Program_Files/character_creation_images/5_inactive_dwarf.gif'
                                anim_delay: 0.05
                                allow_stretch: True
                                keep_ratio: True

                            ToggleButton:
                                id: dwarf_button
                                group: 'species'
                                background_color: (0, 0, 0, 0)
                                background_normal: ''
                                on_press: root.select_species('dwarf')

                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint: (1, 0.3)
                        spacing: 0
                        padding: [50, 0, 50, 100]

                        RelativeLayout:
                            Image:
                                id: warrior_gif
                                source: 'Program_Files/character_creation_images/6_inactive_warrior.gif'
                                anim_delay: 0.05
                                allow_stretch: True
                                keep_ratio: True

                            ToggleButton:
                                id: warrior_button
                                group: 'class'
                                background_color: (0, 0, 0, 0)
                                background_normal: ''
                                on_press: root.select_class('warrior')

                        RelativeLayout:
                            Image:
                                id: ranger_gif
                                source: 'Program_Files/character_creation_images/7_inactive_ranger.gif'
                                anim_delay: 0.05
                                allow_stretch: True
                                keep_ratio: True

                            ToggleButton:
                                id: ranger_button
                                group: 'class'
                                background_color: (0, 0, 0, 0)
                                background_normal: ''
                                on_press: root.select_class('ranger')

                        RelativeLayout:
                            Image:
                                id: mage_gif
                                source: 'Program_Files/character_creation_images/8_inactive_mage.gif'
                                anim_delay: 0.05
                                allow_stretch: True
                                keep_ratio: True

                            ToggleButton:
                                id: mage_button
                                group: 'class'
                                background_color: (0, 0, 0, 0)
                                background_normal: ''
                                on_press: root.select_class('mage')

        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: 0.1
            padding: [10, 15, 10, 15]
            spacing: 15

            HoverButtonRounded:
                text: 'Main Menu'
                font_name: 'Program_Files/fonts/medieval_font_file_2.ttf'
                font_size: 30
                bold: True
                size_hint_x: 0.33
                on_release:
                    root.on_back_button_pressed()
                    root.show_initial_character_image()  # Display character_0.png
                background_color: [0, 0, 0, 0]
                background_normal: ''

            HoverButtonRounded:
                text: 'Choose Random'
                font_name: 'Program_Files/fonts/medieval_font_file_2.ttf'
                font_size: 30
                bold: True
                size_hint_x: 0.34
                on_release: root.random_selection()
                background_color: [0, 0, 0, 0]
                background_normal: ''

            HoverButtonRounded:
                id: create_button
                text: 'Continue'
                font_name: 'Program_Files/fonts/medieval_font_file_2.ttf'
                font_size: 30
                bold: True
                size_hint_x: 0.33
                disabled: True
                on_release:
                    root.on_create_button_pressed()
                    root.show_initial_character_image()  # Display character_0.png
                background_color: [0.5, 0.5, 0.5, 0]
                background_normal: ''

<InGameScreen>:
    id: ingame_screen
    hero_name: ""
    hero_species: ""
    hero_hp: ""
    hero_dmg: ""
    hero_armor: ""

    BoxLayout:
        orientation: 'vertical'
        size_hint_y: 1
        padding: 20
        canvas.before:
            Rectangle:
                source: 'Program_Files/in_game_images/in_game_background.png'
                pos: self.pos
                size: self.size

        BoxLayout:
            size_hint_y: None
            height: 40
            padding: 0
            spacing: 10
            pos_hint: {'top': 1}

            HoverButtonRounded:
                text: 'Back'
                size_hint: (None, None)
                size: (120, 50)
                font_size: 20
                background_color: [0, 0, 0, 0]
                background_normal: ''
                on_release: root.go_back_to_menu(self)

            HoverButtonRounded:
                text: 'Statistics'
                size_hint: (None, None)
                size: (120, 50)
                font_size: 20
                background_color: [0, 0, 0, 0]
                background_normal: ''
                on_release: root.toggle_panel('stats')

            HoverButtonRounded:
                text: 'Inventory'
                size_hint: (None, None)
                size: (120, 50)
                font_size: 20
                background_color: [0, 0, 0, 0]
                background_normal: ''
                on_release: root.toggle_panel('backpack', 'stats')

            HoverButtonRounded:
                text: 'History'
                size_hint: (None, None)
                size: (120, 50)
                font_size: 20
                background_color: [0, 0, 0, 0]
                background_normal: ''

            HoverButtonRounded:
                text: 'Load'
                size_hint: (None, None)
                size: (120, 50)
                font_size: 20
                background_color: [0, 0, 0, 0]
                background_normal: ''

            HoverButtonRounded:
                text: 'Save'
                size_hint: (None, None)
                size: (120, 50)
                font_size: 20
                background_color: [0, 0, 0, 0]
                background_normal: ''

            HoverButtonRounded:
                text: 'Exit'
                size_hint: (None, None)
                size: (120, 50)
                font_size: 20
                background_color: [0, 0, 0, 0]
                background_normal: ''
                on_release: root.exit_app(self)

        # Main content area
        BoxLayout:
            orientation: 'vertical'
            size_hint: (1, 1)
            padding: 20
            spacing: 10
            pos_hint: {'x': 0, 'y': 0}
            # Position the Label at the bottom without affecting the input text
           

            Label:
                id: output_label
                size_hint: (1, 0.8)
                font_size: 16
                color: (1, 1, 1, 1)
                outline_width: 0
                outline_color: (0, 0, 0, 0)
                text_size: (self.width - 40, None)
                padding: (0, 600, 0, 0)
                valign: 'top'
                halign: 'left'

            TextInput:
                id: input_text
                size_hint: (1, 0.045)
                font_size: 30
                font_name: 'Program_Files/fonts/medieval_font_file_2.ttf'
                background_color: (1, 1, 1, 1)
                multiline: False
                padding: (15, 10, 15, 10)
                on_text_validate: root.on_text_enter(self)

                    
    # Stats panel (initially hidden)
    FloatLayout:
        id: stats
        size_hint: (0.601, 0.60)
        pos: (20, 307) # Using pos with fixed value bc pos_hint doesnt work 
        padding: 10
        canvas.before:
            Color:
                rgba: 0, 0, 0, 0.7
            Rectangle:
                pos: self.pos
                size: self.size
        opacity: 0  # Initially hidden
        disabled: True  # Initially disabled

        # Layout title with character name
        Label:
            text: root.hero_name
            color: (1, 1, 1, 1)
            font_size: 36
            font_name: 'Program_Files/fonts/medieval_font_file_2.ttf'
            size_hint: 1, None
            size: self.texture_size
            pos_hint: {'center_x': 0.5, 'top': 1}  # Center horizontally and align to the top
            padding: [15, 15, 15, 15]

        # Content of equipped tab
        BoxLayout:
            orientation: 'horizontal'
            size_hint: 1, 1  # Take all available space in width and height
            size: self.minimum_size             
            pos_hint: {'right': 1, 'top': 1}  # Align to top right

            # BoxLayout for the stats
            BoxLayout:
                size_hint: None, None
                width: 230
                height: self.minimum_height
                pos_hint: {'top': 1}  # Align to top
                # Label for stats
                Label:
                    text: '[b]Species:[/b] ' + root.hero_species + '\n\n[b]HP:[/b] ' + root.hero_hp + '\n\n[b]Damage:[/b] ' + root.hero_dmg + '\n\n[b]Armor:[/b] ' + root.hero_armor
                    markup: True
                    color: (1, 1, 1, 1)
                    font_size: 24
                    font_name: 'Program_Files/fonts/Modesto-Poster-Regular.otf'
                    size_hint: None, None
                    size: self.texture_size
                    pos_hint: {'top': 0.8}  # Center horizontally and align below the title
                    padding: [30]
            

            # BoxLayout for the character picture
            BoxLayout:
                size_hint: 1, None  # Take all available space in width
                height: self.minimum_height
                spos_hint: {'top': 1}  # Align to top
                Image:
                    source: 'Program_Files/char_pics/dwarf.png'
                    size_hint: None, None
                    size: 333, 512  # Set the size of the image
                    pos_hint: {'center_x': 0.5}  # Center horizontally

            # Horizontal BoxLayout for equipped items
            GridLayout:
                cols: 1  # Set the number of columns to 1
                size_hint: None, None
                width: 120  # Set a fixed width for the grid
                size: self.minimum_size
                spacing: 30  # Add spacing between the items
                padding: [30, 30, 30, 30]
                pos_hint: {'right': 1, 'top': 1}  # Align to top right

                # Item containers
                BoxLayout:
                    size_hint: None, None
                    size: 104, 104  # Set the size of the container
                    Image:
                        source: 'Program_Files/items_96p/item-slot.png'
                        size_hint: None, None
                        size: 104, 104  # Set the size of the image to 96x96 pixels

                BoxLayout:
                    size_hint: None, None
                    size: 104, 104  # Set the size of the container
                    Image:
                        source: 'Program_Files/items_96p/item-slot.png'
                        size_hint: None, None
                        size: 104, 104  # Set the size of the image to 96x96 pixels

                BoxLayout:
                    size_hint: None, None
                    size: 104, 104  # Set the size of the container
                    Image:
                        source: 'Program_Files/items_96p/item-slot.png'
                        size_hint: None, None
                        size: 104, 104  # Set the size of the image to 96x96 pixels

        
    
    # Backpack panel (initially hidden)
    FloatLayout:  
        id: backpack
        size_hint: (0.360, 0.60)
        pos_hint: {'right': 0.987, 'top': 0.92}
        orientation: 'vertical'
        padding: 10
        canvas.before:
            Color:
                rgba: 0, 0, 0, 0.7
            Rectangle:
                pos: self.pos
                size: self.size
        opacity: 0  # Initially hidden
        disabled: True  # Initially disabled

        BoxLayout:
            orientation: 'vertical'
            size_hint: None, None
            size: self.minimum_size
            pos_hint: {'x': 0, 'top': 1}  # Align to top left

            Label:
                text: 'BACKPACK'
                color: (1, 1, 1, 1)
                font_size: 24
                font_name: 'Program_Files/fonts/medieval_font_file_2.ttf'
                size_hint: None, None
                size: self.texture_size
                padding: [15, 15, 15, 3]
                pos_hint: {'center_x': 0.5}  # Center horizontally
            
            # Grid Layout for item buttons
            GridLayout:
                id: item_grid
                cols: 4 # Set the number of columns to 4
                size_hint: None, None
                size: self.minimum_size
                spacing: 12  # Add spacing between the items
                padding: [12]  # Add padding to the left


<HoverButton@Button>:
    background_color: 0, 0, 0, 0
    canvas.before:
        Rectangle:
            pos: self.pos
            size: self.size
            source: self.default_image