#:kivy 1.0.9
#:import HoverButton main.HoverButton

ScreenManager:
    MenuScreen:
        name: 'menu'
    CharacterCreation:
        name: 'character_creation'
    InGameScreen:
        name: 'ingame'

<MenuScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: 100, 200, 100, 180
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: 'Program_Files/main_menu_background.jpg'

        HoverButton:
            text: 'New'
            font_name: 'Program_Files/medieval_font_file_2.ttf'
            font_size: 70
            size_hint: 0.2, 0.3
            pos_hint: {'center_x': 0.38}
            default_image: 'Program_Files/original_button_image.png'
            hover_image: 'Program_Files/new_game_button.png'
            on_press: root.change_to_chat()

        HoverButton:
            text: 'Load'
            font_name: 'Program_Files/medieval_font_file_2.ttf'
            font_size: 70
            size_hint: 0.2, 0.3
            pos_hint: {'center_x': 0.62}
            default_image: 'Program_Files/original_button_image.png'
            hover_image: 'Program_Files/load_game_button.png'
            on_press: app.stop()

        HoverButton:
            text: 'Die'
            font_size: 70
            font_name: 'Program_Files/medieval_font_file_2.ttf'
            size_hint: 0.2, 0.3
            pos_hint: {'center_x': 0.49}
            default_image: 'Program_Files/original_button_image.png'
            hover_image: 'Program_Files/exit_game_button.png'
            on_press: app.stop()

<CharacterCreation>:
    BoxLayout:
        orientation: 'vertical'
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: 'Program_Files/background_image.png'  # Ensure this image is in your folder
        
        BoxLayout:
            orientation: 'horizontal'
            size_hint: (1, 0.3)
            spacing: 20
            padding: [50, 0, 50, 0]
            
            Button:
                id: male_button
                background_normal: 'Program_Files/male_image.png'
                background_down: 'Program_Files/male_image_selected.png'
                on_press: app.root.current_screen.ids.male_button.state = 'down'
                on_release: root.select_gender('male')
            
            Button:
                id: female_button
                background_normal: 'Program_Files/female_image.png'
                background_down: 'Program_Files/female_image_selected.png'
                on_press: app.root.current_screen.ids.female_button.state = 'down'
                on_release: root.select_gender('female')

        BoxLayout:
            orientation: 'horizontal'
            size_hint: (1, 0.3)
            spacing: 20
            padding: [50, 0, 50, 0]

            Button:
                id: human_button
                background_normal: 'Program_Files/human_image.png'
                background_down: 'Program_Files/human_image_selected.png'
                on_press: app.root.current_screen.ids.human_button.state = 'down'
                on_release: root.select_species('human')

            Button:
                id: elf_button
                background_normal: 'Program_Files/elf_image.png'
                background_down: 'Program_Files/elf_image_selected.png'
                on_press: app.root.current_screen.ids.elf_button.state = 'down'
                on_release: root.select_species('elf')

            Button:
                id: dwarf_button
                background_normal: 'Program_Files/dwarf_image.png'
                background_down: 'Program_Files/dwarf_image_selected.png'
                on_press: app.root.current_screen.ids.dwarf_button.state = 'down'
                on_release: root.select_species('dwarf')

        BoxLayout:
            orientation: 'horizontal'
            size_hint: (1, 0.3)
            spacing: 20
            padding: [50, 0, 50, 0]

            Button:
                id: warrior_button
                background_normal: 'Program_Files/warrior_image.png'
                background_down: 'Program_Files/warrior_image_selected.png'
                on_press: app.root.current_screen.ids.warrior_button.state = 'down'
                on_release: root.select_class('warrior')

            Button:
                id: ranger_button
                background_normal: 'Program_Files/ranger_image.png'
                background_down: 'Program_Files/ranger_image_selected.png'
                on_press: app.root.current_screen.ids.ranger_button.state = 'down'
                on_release: root.select_class('ranger')

            Button:
                id: mage_button
                background_normal: 'Program_Files/mage_image.png'
                background_down: 'Program_Files/mage_image_selected.png'
                on_press: app.root.current_screen.ids.mage_button.state = 'down'
                on_release: root.select_class('mage')

        BoxLayout:
            orientation: 'horizontal'
            size_hint: (1, 0.1)
            padding: [50, 20, 50, 20]
            spacing: 20
            
            Button:
                text: 'Back'
                on_release: app.root.current = 'menu'

            Button:
                text: 'Create'
                on_release: app.root.current = 'ingame'







<InGameScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: 20
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                source: 'Program_Files/in-game_background.png'
                pos: self.pos
                size: self.size

        BoxLayout:
            size_hint_y: None
            height: 40
            padding: 0
            spacing: 10  # Adjust spacing for better alignment
            pos_hint: {'top': 1}

            HoverButtonRounded:
                text: 'Back'
                size_hint: (None, None)
                size: (120, 50)
                font_size: 20
                background_normal: ''
                background_color: (0.4, 0.7, 0.7, 0)
                on_release: root.go_back_to_menu(self)

            HoverButtonRounded:
                text: 'Statistics'
                size_hint: (None, None)
                size: (120, 50)
                font_size: 20
                background_normal: ''
                background_color: (0.4, 0.7, 0.7, 0)

            HoverButtonRounded:
                text: 'Save'
                size_hint: (None, None)
                size: (120, 50)
                font_size: 20
                background_normal: ''
                background_color: (0.4, 0.7, 0.7, 0)

            HoverButtonRounded:
                text: 'Load'
                size_hint: (None, None)
                size: (120, 50)
                font_size: 20
                background_normal: ''
                background_color: (0.4, 0.7, 0.7, 0)

            HoverButtonRounded:
                text: 'Exit'
                size_hint: (None, None)
                size: (120, 50)
                font_size: 20
                background_normal: ''
                background_color: (0.4, 0.7, 0.7, 0)
                on_release: root.exit_app(self)

        # Main content area
        BoxLayout:
            orientation: 'vertical'
            size_hint: (1, 0.9)

            Label:
                id: output_label
                size_hint: (1, 0.8)
                font_size: 16
                color: (1, 1, 1, 1)
                outline_width: 0
                outline_color: (0, 0, 0, 0)
                text_size: (self.width - 40, None)
                padding: (0, 600, 0, 0)
                valign: 'top'
                halign: 'left'

            TextInput:
                id: input_text
                size_hint: (1, 0.045)
                font_size: 30
                font_name: 'Program_Files/medieval_font_file.ttf'
                background_color: (1, 1, 1, 1)
                multiline: False
                padding: (15, 10, 15, 10)
                on_text_validate: root.on_text_enter(self)

<HoverButton@Button>:
    background_color: 0, 0, 0, 0
    canvas.before:
        Rectangle:
            pos: self.pos
            size: self.size
            source: self.default_image